### PR TITLE
Added getpass to get password

### LINKED ISSUE #1: When password is entered in command line, it is not hidden.
Password entered in the command line is shown as plain text

This is dangerous as it can be seen. Shoulder surfers can hack into your account.

Suggestion: Use `getpass` library.

### PR DESCRIPTION
**Pull request by PjrCodes**
Use getpass library to fix #1

### CODE REVIEW

**Comment by vachanmn123** [comment]
Can you do this for the `main.py` file as well.

**Comment by PjrCodes** [comment]
> Can you do this for the `main.py` file as well.

Alright, sure

**Comment by PjrCodes** [comment]
Done! @vachanmn123

**Comment by vachanmn123** [comment]
Thnx

**Pull request merged**
